package pl.wit.bikerental.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

/**
 * Unit tests for the {@link Types} class.
 * <p>
 * Tests cover both constructors (automatic and manual ID assignment), field accessors and mutators,
 * and the static type ID counter.
 * </p>
 * 
 * @author Krzysztof Mickiewicz
 * @version 1.0
 * @since 2025-06-15
 */
class TypesTest {

    /**
     * Resets the type ID counter before each test to ensure test independence.
     */
    @BeforeEach
    void resetTypeIdCount() {
        Types.setTypeIdCount(0);
    }

    /**
     * Tests creation of a {@link Types} object with an automatically generated ID and verifies all fields.
     */
    @Test
    void testAutoGeneratedIdConstructor() {
        Types type = new Types("Górski", "Rower przystosowany do jazdy w terenie");

        assertEquals("TYP1", type.getId());
        assertEquals("Górski", type.getName());
        assertEquals("Rower przystosowany do jazdy w terenie", type.getDescription());
    }

    /**
     * Tests creation of a {@link Types} object with a manually provided ID and verifies all fields.
     */
    @Test
    void testConstructorWithKnownId() {
        Types type = new Types("TYP99", "Miejski", "Rower do jazdy po mieście");

        assertEquals("TYP99", type.getId());
        assertEquals("Miejski", type.getName());
        assertEquals("Rower do jazdy po mieście", type.getDescription());
    }

    /**
     * Tests all setter methods for the {@link Types} class by updating fields and verifying their values.
     */
    @Test
    void testSetters() {
        Types type = new Types("Trek", "Placeholder");
        type.setName("Trekkingowy");
        type.setDescription("Do jazdy turystycznej");

        assertEquals("Trekkingowy", type.getName());
        assertEquals("Do jazdy turystycznej", type.getDescription());
    }

    /**
     * Tests the static type ID counter, ensuring it increments with new instances.
     */
    @Test
    void testTypeIdCountTracking() {
        assertEquals(0, Types.getTypeIdCount());

        new Types("Górski", "opis");
        new Types("Szosowy", "opis");
        assertEquals(2, Types.getTypeIdCount());
    }
}