package pl.wit.bikerental.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

/**
 *
 * @author Krzysztof Mickiewicz
 * @version 1.0
 * @since 2025-06-15
 */

class TypesTest {

    @BeforeEach
    void resetTypeIdCount() {
        Types.setTypeIdCount(0);
    }

    @Test
    void testAutoGeneratedIdConstructor() {
        Types type = new Types("Górski", "Rower przystosowany do jazdy w terenie");

        assertEquals("TYP1", type.getId());
        assertEquals("Górski", type.getName());
        assertEquals("Rower przystosowany do jazdy w terenie", type.getDescription());
    }

    @Test
    void testConstructorWithKnownId() {
        Types type = new Types("TYP99", "Miejski", "Rower do jazdy po mieście");

        assertEquals("TYP99", type.getId());
        assertEquals("Miejski", type.getName());
        assertEquals("Rower do jazdy po mieście", type.getDescription());
    }

    @Test
    void testSetters() {
        Types type = new Types("Trek", "Placeholder");
        type.setName("Trekkingowy");
        type.setDescription("Do jazdy turystycznej");

        assertEquals("Trekkingowy", type.getName());
        assertEquals("Do jazdy turystycznej", type.getDescription());
    }

    @Test
    void testTypeIdCountTracking() {
        assertEquals(0, Types.getTypeIdCount());

        new Types("Górski", "opis");
        new Types("Szosowy", "opis");
        assertEquals(2, Types.getTypeIdCount());
    }
}